# 服务主要要配置
## http配置
http:
  port: '9003' # http端口

## 任务配置
task:
  log_retention: '720h' # 日志保留时间，最小有效值 24h; 有效的单位："s", "m", "h"。
## 加密
crypto:
  secret: '12345678' # 秘钥 至少8位数字，否则无效

## 用户
user:
  admin_account: "admin" # 管理员账号，设置后页面请求需要登录
  admin_password: "" # 管理员密码